### ISSUE TITLE
Missing 1.6 version from maven repository

### ISSUE THREAD

**Issue by AndreasPresthammer** [makubi/avrohugger-maven-plugin#21]
I cannot find the referenced 1.6 version in the usage documentation on the maven central repository:

https://mvnrepository.com/artifact/at.makubi.maven.plugin/avrohugger-maven-plugin

I only see the 1.5 version as the newest.

Is the 1.6 released somewhere else?

**Comment by makubi** [comment]
Hi, I guess the search index needs some time to update on Maven central.
https://repo1.maven.org/ is more up-to-date than at least the search on https://search.maven.org/.

See https://central.sonatype.org/pages/ossrh-guide.html#releasing-to-central

> Upon release, your component will be published to Central: this typically occurs within 10 minutes, though updates to search can take up to two hours.

I guess this issue is solved as the plugin in version 1.6 can now be found at the link you provided.
